title: StevenWin
description: Personal Ramblings

url: http://www.stevenwin.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: 
 - title: About
   url: /about

social:
   github: 
   twitter: 
   facebook: 
   email: steven.win@outlook.com

google_analytics: #"UA-42859700-3"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/