markdown: redcarpet
highlighter: null
permalink: /:title

url: http://stevenwin.github.io/
baseurl: http://stevenwin.github.io/

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed